apiVersion: batch/v1
kind: Job
metadata:
  name: ${JOB_NAME}
  namespace: default
spec:
  parallelism: 1
  completions: 1
  backoffLimit: 1
  template:
    spec:
      containers:
        - name: training-test
          image: ${IMAGE_NAME}
          env:
            - name: WANDB_API_KEY
              value: a07f9a332409243f4cd7eecffd733b9297f9436e
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: gcs.json
          command: ["torchrun", "--nnodes", "1", "--nproc_per_node",  "8", 
                    "train.py", "--model_id", "DSC-7B-code-assistant-v3-full",
                    "--model_name_or_path", "deepseek-ai/deepseek-coder-6.7b-base",
                    "--gcs_data_path", "glaive_code_assistant_v3.json",
                    "--prompt_key", "question", "--response_key", "answer",
                    "--num_train_epochs",  "2", "--per_device_train_batch_size", "8",
                    "--gradient_accumulation_steps", "4", 
                    "--logging_steps", "10",
                    "--learning_rate", "1e-6",
                    "--eval_steps", "1000",
                    "--use_peft", "False",
                    "--use_fsdp",
                    "--use_activation_checkpointing"
                   ]
          resources:
            limits:
              nvidia.com/gpu: 8
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Never
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  completionMode: NonIndexed
  suspend: false