apiVersion: batch/v1
kind: Job
metadata:
  name: ${JOB_NAME}
  namespace: default
spec:
  parallelism: 1
  completions: 1
  backoffLimit: 1
  template:
    spec:
      containers:
        - name: training-test
          image: ${IMAGE_NAME}
          env:
            - name: WANDB_API_KEY
              value: a07f9a332409243f4cd7eecffd733b9297f9436e
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: gcs.json
          command: ["python", "train.py", 
                    "--model_id", "mistral7B-OSS-instruct",
                    "--model_name_or_path", "mistralai/Mistral-7B-v0.1",
                    "--hf_data_path", "ise-uiuc/Magicoder-OSS-Instruct-75K",
                    "--prompt_key", "problem", "--response_key", "solution",
                    "--num_train_epochs",  "2", "--per_device_train_batch_size", "1",
                    "--gradient_accumulation_steps", "16", 
                    "--logging_steps", "10",
                    "--eval_steps", "1000"
                   ]
          resources:
            limits:
              nvidia.com/gpu: 1
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Never
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  completionMode: NonIndexed
  suspend: false